version: 0.0
os: windows
# files:
#   - source: .
#     destination: /home/ec2-user/spring-boot-mongo/
hooks:
#   AfterInstall:
#    - location: setup.sh
#      timeout: 300
#      runas: root
  ApplicationStart:
   - location: run.bat
     timeout: 300
     runas: root
