name: CI/CD Pipeline2
 on:
  push:
    branches: [ main ] 

jobs: 
  continuous-integration:
    runs-on: ubuntu-latest
    steps:  
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Step 3
      - name: Build Application and Run unit Test
        run: |
          mvn -B package --file student-service/pom.xml
        #touch ${{github.workspace}}/myjar.jar
        #cp ${{github.workspace}}/student-service/student-service-app/target/student-service-app-1.0.0-SNAPSHOT.jar ${{github.workspace}}/myjar
          
        #ls ${{github.workspace}}
#       - uses: actions/upload-artifact@v2
#         with:
#           name: my-artifact
#           path: ${{github.workspace}}/student-service/student-service-app/target/student-service-app-1.0.0-SNAPSHOT.jar           
#       - name: copy file
#         uses: canastro/copy-file-action@master
#         with:
#           source: "${{github.workspace}}/student-service/student-service-app/target/student-service-app-1.0.0-SNAPSHOT.jar"
#           target: "/student-service" 
#       - name: commit jar file
#         uses: EndBug/add-and-commit@v7
#         with:
#           default_author: github_actions
#           message: 'jar commit'
#           add: '*.jar --force'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
     # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment --application-name Git_Application --deployment-group-name development_gropup --deployment-config-name CodeDeployDefault.OneAtATime --github-location repository=${{ github.repository }},commitId=${{ github.sha }}        
#   continuous-deployment:
#     runs-on: windows-latest
#     needs: [continuous-integration]
#     if: github.ref == 'refs/heads/main'
#     steps:
#      # Step 1
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}
#      # Step 2
#       - name: Create CodeDeploy Deployment
#         id: deploy
#         run: |
#           aws deploy create-deployment --application-name Git_Application --deployment-group-name development_gropup --deployment-config-name CodeDeployDefault.OneAtATime --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
